version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: radiowash-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: radiowash
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

  api:
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    container_name: radiowash-api
    ports:
      - '5159:8080'
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres;Database=radiowash;Username=postgres;Password=postgres
    depends_on:
      - postgres
    healthcheck:
      test: ['CMD-SHELL', 'curl -f -k http://localhost:8080/healthz || exit 1']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

volumes:
  postgres-data:
