version: '3.8'

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    container_name: radiowash-api
    ports:
      - '5159:8080'
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=host.docker.internal;Port=54322;Database=postgres;Username=postgres;Password=postgres
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    networks:
      - radiowash

networks:
  radiowash:
    external: true
