version: '3.8'

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    container_name: radiowash-api
    ports:
      - '5159:8080'
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=host.docker.internal;Port=54322;Database=postgres;Username=postgres;Password=postgres;SSL Mode=Disable
      - Supabase__Url=http://host.docker.internal:54321
    extra_hosts:
      - "host.docker.internal:host-gateway"
    # healthcheck:
    #   test: ['CMD-SHELL', 'curl -f -k http://localhost:8080/healthz || exit 1']
    #   interval: 30s
    #   timeout: 10s
    #   retries: 3
    #   start_period: 10s
