FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build-env
WORKDIR /app

# Copy csproj and restore dependencies
COPY *.csproj ./
RUN dotnet restore

# Copy everything else and build
COPY . ./
RUN dotnet publish -c Debug -o out

# Build runtime image
FROM mcr.microsoft.com/dotnet/aspnet:8.0
#
# # Install curl for healthcheck
# RUN apt-get update \
#   && apt-get install -y curl
#
# HEALTHCHECK CMD curl --fail https://localhost:5159/healthz || exit

WORKDIR /app
COPY --from=build-env /app/out .
ENTRYPOINT ["dotnet", "RadioWash.Api.dll"]
