name: Deploy API to Azure App Service

on:
  push:
    branches: [main]
    paths:
      - 'api/**'
      - '.github/workflows/api-deploy.yml'
  workflow_dispatch: # For manual triggers

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Log in to ACR
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and push container image
        uses: docker/build-push-action@v4
        with:
          context: ./api
          file: ./api/Dockerfile
          push: true
          tags: ${{ secrets.ACR_LOGIN_SERVER }}/radiowash-api:${{ github.sha }}

      - name: Deploy to Azure App Service
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'radiowash-api'
          images: '${{ secrets.ACR_LOGIN_SERVER }}/radiowash-api:${{ github.sha }}'

      - name: Set API app settings
        uses: azure/cli@v1
        with:
          inlineScript: |
            az webapp config appsettings set --resource-group radio-wash_group --name radiowash-api --settings \
            "Spotify__ClientId=${{ secrets.SPOTIFY_CLIENT_ID }}" \
            "Spotify__ClientSecret=${{ secrets.SPOTIFY_CLIENT_SECRET }}" \
            "Jwt__Secret=${{ secrets.JWT_SECRET }}"
